# Generated by Django 2.2.7 on 2019-12-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191229_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profilepics/default.jpg', upload_to='profilepics'),
        ),
    ]
